### ISSUE TITLE
spicetify-themes tiny-error

### ISSUE THREAD

**Issue by vanja-san** [TheRandomLabs/Scoop-Spotify#59] opened 2021-08-30 07:53 UTC
I've been getting this error for a while now:

```
[14:43:47]   ~ on ❯  scoop install spicetify-themes
Installing 'spicetify-themes' (2021-08-26T06.47.35) [64bit]
Loading master.zip from cache
Checking hash of master.zip ... ok.
Extracting master.zip ... done.
Running installer script...
Get-Content:
Line |
  16 |  (Get-Content "$env:USERPROFILE\.spicetify\Themes\Elementary\user.css" …
     |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\vanja\.spicetify\Themes\Elementary\user.css' because it does not exist.
InvalidOperation:
Line |
  16 |  (Get-Content "$env:USERPROFILE\.spicetify\Themes\Elementary\user.css" …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
Linking X:\Packages\Scoop\apps\spicetify-themes\current => X:\Packages\Scoop\apps\spicetify-themes\2021-08-26T06.47.35
'spicetify-themes' (2021-08-26T06.47.35) was installed successfully!
```
AND

```
[15:07:12]   ~\..\Themes on ❯  spicetify-apply
spicetify v2.5.0-itsmeow-patch4
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files: OK
Extracting: OK
Preprocessing: OK
OK
success Everything is ready, you can start applying now!
Copying raw assets: OK
Overwriting themed assets: OK
Transferring user.css: OK
Applying additional modifications: OK
Transferring extensions:
error Extension "newRelease.js" not found.
error Extension "queueAll.js" not found.
error Extension "newRelease.js" not found.
error Extension "queueAll.js" not found.
OK
success Spotify is spiced up!
```

**Comment by hozansahin** [comment] 2021-10-30 11:21
@TheRandomLabs I have the same problem. please fix it
I think the error is caused by this line. There is no such theme in spicetify-themes. https://github.com/TheRandomLabs/Scoop-Spotify/blob/e2f93ba776bfb431a00656df992267094ed23dc8/bucket/spicetify-themes.json#L36

**Comment by hozansahin** [comment] 2021-10-30 11:24
> @TheRandomLabs I have the same problem. please fix it I think the error is caused by this line. There is no such theme in spicetify-themes.
> 
> https://github.com/TheRandomLabs/Scoop-Spotify/blob/e2f93ba776bfb431a00656df992267094ed23dc8/bucket/spicetify-themes.json#L36

@itsmeow @afonsojramos

**Comment by itsmeow** [comment] 2021-10-30 11:26
Why am I mentioned? I do not maintain the scoop repository, that would be @TheRandomLabs

**Comment by hozansahin** [comment] 2021-10-30 11:30
> Why am I mentioned? I do not maintain the scoop repository, that would be @TheRandomLabs

Sorry my mistake, I thought it was contributing

**Comment by nexus-codes** [comment] 2021-10-31 13:42
@vanja-san @hozansahin
I've fixed this issue but since @TheRandomLabs is not responding I've [forked this repo](https://github.com/nexus-codes/Scoop-Spotify) and added all the fixes there. Feel free to check it out

**Comment by hozansahin** [comment] 2021-10-31 14:32
> @vanja-san @hozansahin I've fixed this issue but since @TheRandomLabs is not responding I've [forked this repo](https://github.com/nexus-codes/Scoop-Spotify) and added all the fixes there. Feel free to check it out

Thank you for reply

**Comment by afonsojramos** [comment] 2022-01-20 19:46
@vanja-san I think you can close this now.

**Closed** 2022-01-27 15:22 UTC
